"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import source as shared_source
from dataclasses_json import Undefined, dataclass_json
from fabra import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateSource200ApplicationJSON:
    r"""Successfully created source"""
    
    source: Optional[shared_source.Source] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('source'), 'exclude': lambda f: f is None }})

    

@dataclasses.dataclass
class CreateSourceResponse:
    
    content_type: str = dataclasses.field()

    status_code: int = dataclasses.field()

    create_source_200_application_json_object: Optional[CreateSource200ApplicationJSON] = dataclasses.field(default=None)

    r"""Successfully created source"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)

    