"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ConnectionType(str, Enum):
    SNOWFLAKE = 'snowflake'
    BIGQUERY = 'bigquery'
    REDSHIFT = 'redshift'
    MONGODB = 'mongodb'
    WEBHOOK = 'webhook'
