"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class FieldType(str, Enum):
    STRING = 'string'
    INTEGER = 'integer'
    TIMESTAMP = 'timestamp'
    JSON = 'json'
    BOOLEAN = 'boolean'
